### ISSUE TITLE
Use vendoring for your dependencies

### ISSUE THREAD

**Issue by benma** [facebookgo/httpdown#6]
Hi

Since Go 1.6, it is recommended to vendor the dependencies:

https://golang.org/doc/go1.6#go_command

Could you do this in this project? I.e. vendor facebookgo/clock and facebookgo/stats (I recommend git submodules, it works great in my projects).

This way, the exact version of the dependencies is fixed, and in my project, I only have to directly depend on httpdown, and not manually transitively vendor all its dependencies.

Thank you.

**Comment by daaku** [comment]
Our strategy is to vendor in our binary packages, not in our library packages. Transitively vendoring the dependencies is what I suggest.

**Comment by benma** [comment]
Thanks. That is a pity though, as it makes maintaining this library as a dependency much harder (i.e. it is harder to track which libraries are my direct deps, vs. deps of my deps).

Also consider that in general, some libraries might be dependencies of multiple libraries, but in different versions (i.e. if we do not upgrade them at once). Vendoring recursively solves that problem as well.

**Comment by daaku** [comment]
IMO it isn't much harder. It's can also be cleaner (and cause less bloat) because if the same library is used elsewhere each vendored copy is a copy in the final binary. Also the strategy doesn't work if you need to share types from your dependencies.
