### ISSUE TITLE
add tcpKeepAliveListener

### ISSUE THREAD

**Issue by jmhodges** [facebookgo/httpdown#7]
The `net/http` code uses its own `tcpKeepAliveListener` in its Listen helpers to prevent expired TCP connections from remaining open too long (e.g. laptops being closed mid-download).

I think it makes sense for httpdown to do the same. I don't see equivalent code to it.

Does this make sense to y'all?

Example usage here: https://github.com/golang/go/blob/c80e0d374ba3caf8ee32c6fe4a5474fa33928086/src/net/http/server.go#L2219

**Comment by SunRunAway** [comment]
Any plan about this? It bites us.

**Comment by daaku** [comment]
Since Go 1.8 will include graceful shutdown in the standard library itself 😃, I think it's best to switch to that once it's out rather than making improvements to this library.

**Comment by matthewmueller** [comment]
@daaku FWIW, I'm looking into this library because the shutdown function also closes the listener, so reloads don't really work. see: https://github.com/golang/go/issues/19556#issuecomment-286780000

**Comment by matthewmueller** [comment]
Nevermind! I think I was doing something wrong in my application code. Closing a listener shouldn't affect other listeners on the same socket.

If anyone wants to piggyback off this work, it's basically this https://github.com/facebookgo/httpdown/blob/a3b1354551a26449fbe05f5d855937f6e7acbd71/httpdown.go#L343-L376 modified for 1.8:

```go
stdinServer := http.Server{
	Handler: http.HandlerFunc(handler),
}

waiterr := make(chan error, 1)
go func() {
	waiterr <- stdinServer.Serve(stdinListener)
}()

signals := make(chan os.Signal)
signal.Notify(signals, syscall.SIGTERM, syscall.SIGINT)
select {
case err := <-waiterr:
	if err != nil {
		log.WithError(err).Error("serve err")
		return
	}
case <-signals:
	signal.Stop(signals)
	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Minute)
	defer cancel()
	if err := stdinServer.Shutdown(ctx); err != nil {
		log.WithError(err).Error("stop err")
		return
	}
	if err := <-waiterr; err != nil && err != http.ErrServerClosed {
		log.WithError(err).Error("serve err")
		return
	}
}
```

I tested it with a stress test and reloading a bunch and there was zero downtime :-)
